<?php
if (isset($_POST['quote-submit'])) {
  ini_set("include_path", '/home/ahysfxiz/php:' . ini_get("include_path") );

  $title = $_POST['ti'];
  $fullName = $_POST['name'];
  $email = $_POST['email'];
  $phno = $_POST['phno'];
  $service = $_POST['service'];
  $pscd = $_POST['pscd'];
  $description = $_POST['description'];
  require 'PhpMailer/PHPMailerAutoload.php';
  $mail = new PhpMailer();

//Method that checks empty fields and returns the user to contact with the valid info autofilled
  if (empty($title) || empty($fullName) || empty($email) || empty($phno) || empty($service) || empty($pscd) || empty($description)) {
    header("Location: ../../getaquote.php?error=emptyfields&ti=".$title."&name=".$fullName."&email=".$email."&phno=".$phno."&service=".$service."&pscd=".$pscd."&description=".$description);
    exit();
  }

  //Method that checks if the First Name entered is valid and returns the user to contact with the valid info autofilled
  elseif (!preg_match("/^[a-zA-Z\s]*$/",$title)) {
    header("Location: ../../getaquote.php?error=invalidtitle&name=".$fullName."&email=".$email."&phno=".$phno."&pscd=".$pscd."&description=".$description);
    exit();
  }

  //Method that checks if the Last Name entered is valid and returns the user to contact with the valid info autofilled
  elseif (!preg_match("/^[a-zA-Z\s]*$/",$fullName)) {
    header("Location: ../../getaquote.php?error=invalidfullName&ti=".$title."&email=".$email."&phno=".$phno."&pscd=".$pscd."&description=".$description);
    exit();
  }

  //Method that checks if the Email entered is valid and returns the user to contact with the valid info autofilled
  elseif (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
    header("Location: ../../getaquote.php?error=invalidEmail&ti=".$title."&name=".$fullName."&phno=".$phno."&pscd=".$pscd."&description=".$description);
    exit();
  }

    //Method that checks if the message entered is valid and returns the user to contact with the valid info autofilled
  elseif (!preg_match("/^[0-9]*$/",$phno)) {
    header("Location: ../../getaquote.php?error=invalidPhoneNumber&ti=".$title."&name=".$fullName."&email=".$email."&pscd=".$pscd."&description=".$description);
    exit();
  }

      //Method that checks if the message entered is valid and returns the user to contact with the valid info autofilled
  elseif (!preg_match("/^[a-zA-Z0-9\s]*$/",$pscd)) {
    header("Location: ../../getaquote.php?error=invalidPostcode&ti=".$title."&name=".$fullName."&email=".$email."&phno=".$phno."&description=".$description);
    exit();
  }

      //Method that checks if the message entered is valid and returns the user to contact with the valid info autofilled
  elseif (!preg_match("/^[a-zA-Z0-9.?,!\s]*$/",$description)) {
    header("Location: ../../getaquote.php?error=invalidDescription&ti=".$title."&name=".$fullName."&email=".$email."&phno=".$phno."&pscd=".$pscd);
    exit();
  }
  else {
      $message = "Email generated by Easy Fix website on behalf of: \r\n";
      $message .= $title." ";
      $message .= $fullName."\r\n";
      $message .= $service.": ".$pscd."\r\n";
      $message .= "\r\n Email message: \r\n";
      $message .= $description."\r\n";
      $message .= "Contact details: \r\n";
      $message .= "Email:  ".$email." \r\n";
      $message .= "Telephone:  ".$phno."\r\n";
      $message .= "Client has accepted to be contacted back via phone call.";
       // SMTP Configuration
      $mail->SMTPAuth = true; 
      $mail->IsSMTP();
      $mail->Host = "mail.easyfixpm.co.uk"; // SMTP server
      $mail->Username = "test@easyfixpm.co.uk";
      $mail->Password = "B3nj@mjn";
      $mail->SMTPSecure = 'tls';   
      $mail->Port = 465;

      $mail->AddAddress('test@easyfixpm.co.uk');
      $mail->From = $email;
      $mail->FromName = "EasyFix Quote Request";
      $mail->Subject = 'Inquiry from: '.$fullName;

      $mail->Body    = $message;    
      $mail->AltBody = "To view the message, please use an HTML compatible email viewer!"; // optional, comment out and test
      $mail->MsgHTML("Name:".$title . $fullName . "<br /><br />Email:" . $email. "<br /><br />Telephone:" . $phno. "<br /><br />Subject:" . $service. "<br /><br />" . $pscd);

      $message = NULL;
    if(!$mail->Send()) {
        $message = "Mailer Error: " . $mail->ErrorInfo;
    } else {
        $message = "Message sent!";
    }

      //Sending an copy of the enquery to the contact-us email
      // $to = "test@easyfixpm.co.uk";
      // $subject = 'Inquiry from: '.$email;
      // $message = "Email generated by Easy Fix website on behalf of: \r\n";
      // $message .= $title." ";
      // $message .= $fullName."\r\n";
      // $message .= $service.": ".$pscd."\r\n";
      // $message .= "\r\n Email message: \r\n";
      // $message .= $description."\r\n";
      // $message .= "Contact details: \r\n";
      // $message .= "Email:  ".$email." \r\n";
      // $message .= "Telephone:  ".$phno."\r\n";
      // $message .= "Client has accepted to be contacted back via phone call.";
      // $headers = "From:".$email."\r\n";
      // $headers .= "Reply-to:".$email."\r\n";
      // $headers .= "X-Mailer: PHP/".phpversion();
      // mail($to, $subject, $message, $headers);
      // header("Location: ../../getaquote.php?quote-submit=success");
      exit();
    }
}
else {
  header("Location: ../../getaquote.php");
  exit();
}
